/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateKeyDialog: typeof import('./components/CreateKeyDialog.vue')['default']
    DeleteKeyButton: typeof import('./components/DeleteKeyButton.vue')['default']
    KeyRevealDialog: typeof import('./components/KeyRevealDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}
